name: Unzip and Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Base Zip
        run: |
          if [ -f "Base phising.zip" ]; then
            unzip -o "Base phising.zip"
            rm "Base phising.zip"
          else
            echo "❌ Berkas Base phising.zip tidak ditemukan di root repository!"
            exit 1
          fi

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APK Release
        run: flutter build apk --release --split-per-abi

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: X-Nose-Infinity-APK
          path: build/app/outputs/flutter-apk/*.apk
